language: node_js
node_js:
- '8'
deploy:
  # tag: 'beta'
  provider: npm
  email: wojciech.g.krysiak@gmail.com
  api_key:
    secure: XccQzN+oE24xUOCuwuYjLwZOwslkq0Woxp6gdL+AL9Hw5ao88N79tGkC26EabPPD3OFwRddrfLpQROJTBO1OI9nMq6FmdWtrMpv9xo1npII6shxbCvl18/NB+uqPbhlPDxcwzULr5kYnhXDxEvGYkowOFAqJoa7f+QToMxSS7ICEYUCubfDNkF4d+U+yjlKRIKKURI1PO/0CsnnwQtEStVdk8Lr9UrpV4EUmBV+7NLtW9NcBKfOQt7sGQXR/HiXFzka5kIj3tDW0uhZvZykRHU3j6LxDJhCReBPAaW+S1yOB5BsLaYpo1bOzhhBl4FbPYtDZhW1P6f5gQ+VU3/EvLBxKFBBjeGQAxS6v7dCvHdR4l50LWK7b/up2WoWgew+b9tLuV8hRUchtusFNE8UVNGpsWRGGS5bziK/A1CwynbViuAR3jl5qIByzSWDYCsJ3i31Ptb6C/uq5rKOtaLmtxQeF7uFUUm1tJPe/7Kr1DizAQMccxnL+ursjPNbcDUhMT6f87OUhK8jk0oU9aPBWu+65+d105wVxTxFJwful4kIziS4E/261hPzavSYTXA8ki6Vd0w4849nHMGWM8kZgqC6inS4iYzFJkrGhWSjxFCUmZyuAA3yHizlYS7eINhgK8wqk2XR/tUYLkfSPW6xmb9xDircqgdxzv8g4nBXCdx4=
  on:
    tags: true
    repo: SoftwareBrothers/better-docs
notifications:
  slack:
    secure: kuyxSwmyGhCjGRMzbgxCDiOSUzA9m+/eOUgRhIB0CNyWC3XL5ZstB7n1zA8J1bFe80TxFvHawhkT0WWoS0LVhDj7NRxZxBNHVZFKtM1iAU5zaf4s/x6JNA0S6w78240yJPOW1ViwX98jqSGGmu0uaq+8DvLpC1gdSDa35gHSq0F3N5VFqzmpbqMY9OkhhcepU90uP4jlwS2T3mp2s5MML7Z26uia8Q5QfLAMaaC7zNYS0jZPj+37cwTzt73u9Dxc1NYMg6mCsD8nmV6Kij5dBLJlc3rRIOR3mP0THS6BykEdTFI51Gl1bNCvPntrE/IUOtBKoI8KcTXAzxXQZrC9tWRYE+VeaTiwmrjAv2CkI+XOsJldJGE3nsKQ59YH7gk4XkRfDMjzRpyqMGKA3fndAh8Yi60tojoJBCF4HAUTqcmRh/RFnus8kceWIhy56Ln1BwUGIXAhlc0WKkKkPIDo1UXoOaC9sRzWuK6Vd33woRlSsP3FGPKCMqbxbn9f9OJ0c/0oyRlOoR0Aigggnkejs5QpitBg4xFN83nsy4E2L3K1fMQb6ZbJjEgmydcDHEPSRzWLC1LsaEiQRFCFKuGtgoTgWo+/hzeG4y4SCl+9v5TtLdZAoPmU+0pQc863LTEyk+Oi9x7AXNoYJYyXjkcwW654D6fykHB2WUWH5a3PEtc=
